Backend code review
Ayush-kumar1/Social-media-backend-submission pull request #1
Opened 2021-06-24 13:40 UTC by Ayush-kumar1

Please review the backend code for social media app

2021-07-07 07:41 UTC, rohiraanjali requested changes
There are some changes in the backend code as well. Look at the PR comments and make changes accordingly.

2021-07-07 07:41 UTC, rohiraanjali commented on server.js
> +const dbURL = "mongodb+srv://admin:PhFK3sbXy5WZJeG4@cluster0.nduys.mongodb.net/SocialMediaDB?retryWrites=true&w=majority";
Backend review -> starting. 

This is a secret key and should not be open to everyone. store it in .env/key.js file and then to .gitignore

2021-07-07 07:41 UTC, rohiraanjali commented on server.js
> +mongoose.connect(dbURL, {
Make a separate file and folder for the Database and store it there.

2021-07-07 07:41 UTC, rohiraanjali commented on routes/auth.js
> +            }
The code inside the routes file is huge. Make a controller folder and put all the CRUD operations there and just refer the functions name in routes files when you do get, post, delete, update. Do this for all the files of routes i.e. auth, user, post.

2021-07-07 07:41 UTC, rohiraanjali commented on routes/auth.js
> +                        // return res.json({ message: "Login sucessful" })
remove all the commented-out code through out the codebase

2021-07-09 14:37 UTC, thesudeshdas requested changes

2021-07-09 14:37 UTC, thesudeshdas commented on key.js
> +export const JWT_SECRET = "ayush_Token";
This should be hidden

2021-07-10 14:48 UTC, merged